import * as THREE from 'three'
import type { AquascapeLayoutStyle } from '../../types/aquarium'
import type { PlantLayer, PlantMassRole, PlantType } from './aquascapePlants'

type HardscapePlantHost = 'driftwood' | 'rock'

export type HardscapePlantAnchor = {
  id: string
  host: HardscapePlantHost
  massRole: PlantMassRole
  layer: PlantLayer
  plantType: Exclude<PlantType, 'ribbon-seaweed'>
  position: THREE.Vector3
  rotation: THREE.Euler
  scale: THREE.Vector3
  height: number
  hueBase: number
  assetIds?: string[]
}

const cloneHardscapePlantAnchor = (anchor: HardscapePlantAnchor): HardscapePlantAnchor => ({
  ...anchor,
  position: anchor.position.clone(),
  rotation: anchor.rotation.clone(),
  scale: anchor.scale.clone(),
  assetIds: anchor.assetIds ? [...anchor.assetIds] : undefined
})

const plantedHardscapePlantAnchors: HardscapePlantAnchor[] = [
  {
    id: 'driftwood-branch-crotch-left',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-1.28, 0.96, 0.64),
    rotation: new THREE.Euler(-0.18, -0.18, 0.12),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.28,
    hueBase: 0.27,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-root-flare-pocket',
    host: 'driftwood',
    massRole: 'root-flare',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-0.82, 0.58, -0.2),
    rotation: new THREE.Euler(-0.26, 0.2, 0.1),
    scale: new THREE.Vector3(0.28, 0.28, 0.28),
    height: 1.42,
    hueBase: 0.255,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-branch-crotch-upper',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(0.34, 1.9, 0.82),
    rotation: new THREE.Euler(-0.22, 0.5, -0.04),
    scale: new THREE.Vector3(0.28, 0.28, 0.28),
    height: 1.92,
    hueBase: 0.292,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'driftwood-branch-crotch-right',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(1.18, 2.18, 0.24),
    rotation: new THREE.Euler(-0.2, -0.28, 0.08),
    scale: new THREE.Vector3(0.3, 0.3, 0.3),
    height: 2.08,
    hueBase: 0.304,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'driftwood-branch-crotch-rear',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.24, 1.46, -0.12),
    rotation: new THREE.Euler(-0.16, -0.14, 0.08),
    scale: new THREE.Vector3(0.24, 0.24, 0.24),
    height: 1.58,
    hueBase: 0.266,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-left',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-0.22, 0.44, 0.18),
    rotation: new THREE.Euler(-0.2, 0.18, 0.22),
    scale: new THREE.Vector3(0.24, 0.24, 0.24),
    height: 1.24,
    hueBase: 0.262,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-center',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(0.54, 0.56, 0.02),
    rotation: new THREE.Euler(-0.18, -0.24, 0.16),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.66,
    hueBase: 0.286,
    assetIds: ['plant-matsumo']
  }
]

const natureShowcaseHardscapePlantAnchors: HardscapePlantAnchor[] = [
  {
    id: 'driftwood-branch-crotch-left',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-1.68, 0.76, 0.66),
    rotation: new THREE.Euler(-0.24, -0.24, 0.16),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.22,
    hueBase: 0.268,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-fork-pocket-lower',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-1.36, 0.92, 0.42),
    rotation: new THREE.Euler(-0.24, 0.12, 0.14),
    scale: new THREE.Vector3(0.24, 0.24, 0.24),
    height: 1.18,
    hueBase: 0.252,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-root-flare-pocket',
    host: 'driftwood',
    massRole: 'root-flare',
    layer: 'midground',
    plantType: 'willow-moss',
    position: new THREE.Vector3(-1.18, 0.52, -0.06),
    rotation: new THREE.Euler(-0.28, 0.3, 0.1),
    scale: new THREE.Vector3(0.18, 0.16, 0.2),
    height: 0.72,
    hueBase: 0.286,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-fork-pocket-upper',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(0.42, 2.06, 0.72),
    rotation: new THREE.Euler(-0.26, 0.56, -0.06),
    scale: new THREE.Vector3(0.26, 0.26, 0.26),
    height: 1.92,
    hueBase: 0.294,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'driftwood-fork-pocket-right',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(1.52, 2.34, 0.3),
    rotation: new THREE.Euler(-0.22, -0.32, 0.06),
    scale: new THREE.Vector3(0.24, 0.24, 0.24),
    height: 1.98,
    hueBase: 0.286,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'driftwood-branch-crotch-rear',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.82, 1.54, -0.04),
    rotation: new THREE.Euler(-0.18, -0.14, 0.08),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.52,
    hueBase: 0.262,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-fork-pocket-rear',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(-0.36, 1.98, 0.08),
    rotation: new THREE.Euler(-0.18, 0.34, -0.08),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.68,
    hueBase: 0.284,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'driftwood-branch-crotch-lower-left',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-1.48, 0.8, 0.54),
    rotation: new THREE.Euler(-0.22, -0.16, 0.14),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.16,
    hueBase: 0.258,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-root-flare-left',
    host: 'driftwood',
    massRole: 'root-flare',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-1.34, 0.48, 0.12),
    rotation: new THREE.Euler(-0.26, 0.22, 0.12),
    scale: new THREE.Vector3(0.24, 0.24, 0.24),
    height: 1.18,
    hueBase: 0.25,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-root-flare-center',
    host: 'driftwood',
    massRole: 'root-flare',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.94, 0.66, 0.18),
    rotation: new THREE.Euler(-0.22, 0.18, 0.08),
    scale: new THREE.Vector3(0.24, 0.24, 0.24),
    height: 1.26,
    hueBase: 0.256,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-fork-pocket-center',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(0.14, 1.84, 0.46),
    rotation: new THREE.Euler(-0.24, 0.3, -0.06),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.72,
    hueBase: 0.286,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'driftwood-fork-junction-center',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(0.74, 2.18, 0.54),
    rotation: new THREE.Euler(-0.22, 0.42, -0.1),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.62,
    hueBase: 0.29,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'driftwood-fork-junction-upper-right',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(1.18, 2.28, 0.42),
    rotation: new THREE.Euler(-0.2, -0.12, 0.08),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.2,
    hueBase: 0.258,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-branch-crotch-right',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(1.82, 2.1, 0.2),
    rotation: new THREE.Euler(-0.18, -0.4, 0.04),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.84,
    hueBase: 0.284,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'driftwood-root-flare-shoulder',
    host: 'driftwood',
    massRole: 'root-flare',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(-1.04, 0.74, 0.24),
    rotation: new THREE.Euler(-0.24, 0.28, 0.06),
    scale: new THREE.Vector3(0.26, 0.26, 0.26),
    height: 1.54,
    hueBase: 0.286,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'driftwood-fork-junction-left-mid',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(-0.52, 1.46, 0.3),
    rotation: new THREE.Euler(-0.2, 0.22, -0.04),
    scale: new THREE.Vector3(0.24, 0.24, 0.24),
    height: 1.74,
    hueBase: 0.288,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'driftwood-fork-pocket-center-left',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.18, 1.62, 0.22),
    rotation: new THREE.Euler(-0.2, 0.24, 0.08),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.22,
    hueBase: 0.258,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-branch-crotch-root-bridge',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-1.12, 0.66, 0.34),
    rotation: new THREE.Euler(-0.22, 0.18, 0.12),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.18,
    hueBase: 0.252,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-root-flare-front-left',
    host: 'driftwood',
    massRole: 'root-flare',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-1.54, 0.56, 0.24),
    rotation: new THREE.Euler(-0.24, 0.18, 0.12),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.22,
    hueBase: 0.252,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-root-flare-right-pocket',
    host: 'driftwood',
    massRole: 'root-flare',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.76, 0.6, 0.28),
    rotation: new THREE.Euler(-0.22, 0.24, 0.08),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.28,
    hueBase: 0.256,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-fork-junction-bridge',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(-0.86, 1.28, 0.44),
    rotation: new THREE.Euler(-0.2, 0.18, -0.04),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.62,
    hueBase: 0.286,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'driftwood-fork-pocket-shoulder',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(-0.28, 1.8, 0.36),
    rotation: new THREE.Euler(-0.22, 0.24, -0.06),
    scale: new THREE.Vector3(0.24, 0.24, 0.24),
    height: 1.78,
    hueBase: 0.286,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'driftwood-branch-crotch-center-upper',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(0.26, 1.98, 0.34),
    rotation: new THREE.Euler(-0.2, 0.28, 0.08),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.18,
    hueBase: 0.252,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-fork-junction-uplift',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(0.94, 2.24, 0.26),
    rotation: new THREE.Euler(-0.18, 0.34, -0.08),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.58,
    hueBase: 0.29,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'driftwood-root-flare-fern-mat',
    host: 'driftwood',
    massRole: 'root-flare',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(-1.22, 0.82, 0.26),
    rotation: new THREE.Euler(-0.24, 0.22, 0.08),
    scale: new THREE.Vector3(0.24, 0.24, 0.24),
    height: 1.62,
    hueBase: 0.284,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'driftwood-fork-pocket-shoulder-left',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.64, 1.72, 0.38),
    rotation: new THREE.Euler(-0.2, 0.2, 0.08),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.24,
    hueBase: 0.258,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'driftwood-fork-junction-center-right',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(0.58, 2.06, 0.4),
    rotation: new THREE.Euler(-0.2, 0.3, -0.06),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.74,
    hueBase: 0.286,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'driftwood-branch-crotch-tip-pocket',
    host: 'driftwood',
    massRole: 'branch-crotch',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(1, 2.08, 0.14),
    rotation: new THREE.Euler(-0.18, 0.12, 0.08),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.16,
    hueBase: 0.252,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-left',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-0.38, 0.34, 0.24),
    rotation: new THREE.Euler(-0.24, 0.18, 0.18),
    scale: new THREE.Vector3(0.22, 0.22, 0.22),
    height: 1.18,
    hueBase: 0.258,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'wood-rock-junction-left',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.58, 0.52, 0.06),
    rotation: new THREE.Euler(-0.22, 0.24, 0.14),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.26,
    hueBase: 0.248,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-center',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(0.12, 0.46, -0.04),
    rotation: new THREE.Euler(-0.2, -0.26, 0.12),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.52,
    hueBase: 0.282,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'rock-crevice-front',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.04, 0.28, 0.26),
    rotation: new THREE.Euler(-0.18, 0.08, 0.14),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.18,
    hueBase: 0.256,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'wood-rock-junction-front',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(-0.14, 0.62, 0.08),
    rotation: new THREE.Euler(-0.18, -0.18, 0.08),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.48,
    hueBase: 0.276,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'rock-crevice-rear-left',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-0.52, 0.42, -0.02),
    rotation: new THREE.Euler(-0.22, 0.16, 0.12),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.14,
    hueBase: 0.252,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-shoulder',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(0.26, 0.58, 0.06),
    rotation: new THREE.Euler(-0.2, -0.24, 0.1),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.44,
    hueBase: 0.282,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'wood-rock-junction-rear',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.28, 0.56, -0.08),
    rotation: new THREE.Euler(-0.18, 0.2, 0.1),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.18,
    hueBase: 0.254,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-root-flare-left',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(-0.74, 0.48, 0.18),
    rotation: new THREE.Euler(-0.18, 0.18, 0.1),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.54,
    hueBase: 0.278,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'wood-rock-junction-center-left',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-0.42, 0.6, 0.12),
    rotation: new THREE.Euler(-0.2, 0.22, 0.12),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.16,
    hueBase: 0.254,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-left-front-low',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-0.66, 0.28, 0.22),
    rotation: new THREE.Euler(-0.24, 0.16, 0.14),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.12,
    hueBase: 0.252,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-left-mid',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(-0.48, 0.48, 0.18),
    rotation: new THREE.Euler(-0.22, 0.18, 0.1),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.44,
    hueBase: 0.282,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'wood-rock-junction-left-shoulder',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.62, 0.62, 0.14),
    rotation: new THREE.Euler(-0.22, 0.22, 0.1),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.2,
    hueBase: 0.256,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-center-left',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(-0.26, 0.54, 0.02),
    rotation: new THREE.Euler(-0.2, 0.14, 0.08),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.52,
    hueBase: 0.278,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'rock-crevice-center-front',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(0.02, 0.36, 0.18),
    rotation: new THREE.Euler(-0.18, 0.08, 0.12),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.14,
    hueBase: 0.252,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'wood-rock-junction-center',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(-0.18, 0.68, -0.02),
    rotation: new THREE.Euler(-0.18, 0.18, 0.08),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.42,
    hueBase: 0.282,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'rock-crevice-root-flare-center-left',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-large',
    position: new THREE.Vector3(-0.56, 0.66, 0.18),
    rotation: new THREE.Euler(-0.2, 0.18, 0.12),
    scale: new THREE.Vector3(0.2, 0.2, 0.2),
    height: 1.56,
    hueBase: 0.28,
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'wood-rock-junction-left-base',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-petite-clump',
    position: new THREE.Vector3(-0.72, 0.4, 0.12),
    rotation: new THREE.Euler(-0.22, 0.18, 0.12),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.14,
    hueBase: 0.252,
    assetIds: ['plant-willow-moss']
  },
  {
    id: 'rock-crevice-mound-shoulder',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'javafern-narrow',
    position: new THREE.Vector3(-0.34, 0.62, 0.16),
    rotation: new THREE.Euler(-0.2, 0.14, 0.08),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.46,
    hueBase: 0.282,
    assetIds: ['plant-matsumo']
  },
  {
    id: 'wood-rock-junction-front-left',
    host: 'rock',
    massRole: 'rock-crevice',
    layer: 'midground',
    plantType: 'anubias-nana-clump',
    position: new THREE.Vector3(-0.46, 0.46, 0.24),
    rotation: new THREE.Euler(-0.2, 0.12, 0.12),
    scale: new THREE.Vector3(0.18, 0.18, 0.18),
    height: 1.18,
    hueBase: 0.256,
    assetIds: ['plant-willow-moss']
  }
]

export const resolveHardscapePlantAnchors = (
  layoutStyle: AquascapeLayoutStyle = 'planted'
): HardscapePlantAnchor[] => (
  layoutStyle === 'nature-showcase'
    ? natureShowcaseHardscapePlantAnchors
    : plantedHardscapePlantAnchors
).map(cloneHardscapePlantAnchor)
