import * as THREE from 'three'
import type { PlantClusterDefinition } from './aquascapePlantTypes'

export const PLANTED_PLANT_CLUSTER_DEFINITIONS: PlantClusterDefinition[] = [
  {
    id: 'front-left',
    x: -0.26,
    z: 0.18,
    layer: 'foreground',
    massRole: 'front-left',
    plantType: 'anubias-petite-clump',
    baseHeight: 1.18,
    spreadX: 0.18,
    spreadZ: 0.12,
    hueBase: 0.27,
    rotationY: -0.18,
    scale: new THREE.Vector3(0.62, 0.58, 0.68),
    heightMin: 0.82,
    heightMax: 1.24,
    coreCount: 1,
    satelliteCount: 1,
    offshootCount: 0,
    coreRadius: [0.02, 0.1],
    satelliteRadius: [0.12, 0.3],
    offshootRadius: [0.3, 0.5],
    minDistance: 0.052,
    depthLaneCount: 2,
    plantMix: [
      { plantType: 'anubias-petite-clump', weight: 0.76 },
      { plantType: 'anubias-nana-clump', weight: 0.24 }
    ],
    assetIds: ['plant-willow-moss', 'plant-willow-moss']
  },
  {
    id: 'left-rear',
    x: -0.34,
    z: -0.25,
    layer: 'background',
    massRole: 'left-rear',
    plantType: 'vallisneria-tall',
    baseHeight: 10.18,
    spreadX: 0.38,
    spreadZ: 0.26,
    hueBase: 0.245,
    rotationY: -0.34,
    scale: new THREE.Vector3(1.18, 2.68, 1.06),
    heightMin: 9.24,
    heightMax: 10.92,
    coreCount: 1,
    satelliteCount: 2,
    offshootCount: 1,
    coreRadius: [0.04, 0.18],
    satelliteRadius: [0.22, 0.58],
    offshootRadius: [0.54, 0.94],
    minDistance: 0.064,
    depthLaneCount: 4,
    plantMix: [
      { plantType: 'vallisneria-tall', weight: 0.66 },
      { plantType: 'hygrophila-rear', weight: 0.1 },
      { plantType: 'stem-green-bush', weight: 0.24 }
    ],
    assetIds: ['plant-vallisneria-tall', 'plant-hygrophila-rear', 'plant-hygrophila-rear']
  },
  {
    id: 'left-shoulder',
    x: -0.2,
    z: -0.04,
    layer: 'midground',
    massRole: 'left-shoulder',
    plantType: 'javafern-large',
    baseHeight: 4.92,
    spreadX: 0.24,
    spreadZ: 0.18,
    hueBase: 0.29,
    rotationY: -0.12,
    scale: new THREE.Vector3(0.96, 1.14, 1),
    heightMin: 3.86,
    heightMax: 5.42,
    coreCount: 1,
    satelliteCount: 2,
    offshootCount: 1,
    coreRadius: [0.03, 0.12],
    satelliteRadius: [0.16, 0.38],
    offshootRadius: [0.36, 0.66],
    minDistance: 0.058,
    depthLaneCount: 3,
    plantMix: [
      { plantType: 'javafern-large', weight: 0.54 },
      { plantType: 'javafern-narrow', weight: 0.2 },
      { plantType: 'anubias-nana-clump', weight: 0.26 }
    ],
    assetIds: ['plant-amazon-sword', 'plant-matsumo', 'plant-willow-moss']
  },
  {
    id: 'front-center',
    x: -0.02,
    z: 0.02,
    layer: 'midground',
    massRole: 'front-center',
    plantType: 'javafern-large',
    baseHeight: 4.12,
    spreadX: 0.22,
    spreadZ: 0.16,
    hueBase: 0.305,
    rotationY: 0.06,
    scale: new THREE.Vector3(0.86, 0.98, 0.88),
    heightMin: 3.34,
    heightMax: 4.84,
    coreCount: 1,
    satelliteCount: 1,
    offshootCount: 1,
    coreRadius: [0.03, 0.16],
    satelliteRadius: [0.16, 0.34],
    offshootRadius: [0.3, 0.54],
    minDistance: 0.056,
    depthLaneCount: 3,
    plantMix: [
      { plantType: 'javafern-large', weight: 0.42 },
      { plantType: 'javafern-narrow', weight: 0.32 },
      { plantType: 'anubias-nana-clump', weight: 0.26 }
    ],
    assetIds: ['plant-amazon-sword', 'plant-matsumo', 'plant-willow-moss']
  },
  {
    id: 'mid-right-backfill',
    x: 0.18,
    z: -0.08,
    layer: 'midground',
    massRole: 'mid-right-backfill',
    plantType: 'crypt-brown',
    baseHeight: 4.08,
    spreadX: 0.2,
    spreadZ: 0.16,
    hueBase: 0.072,
    rotationY: 0.2,
    scale: new THREE.Vector3(0.86, 1.04, 0.8),
    heightMin: 2.84,
    heightMax: 5.42,
    coreCount: 1,
    satelliteCount: 2,
    offshootCount: 1,
    coreRadius: [0.03, 0.12],
    satelliteRadius: [0.14, 0.34],
    offshootRadius: [0.28, 0.5],
    minDistance: 0.056,
    depthLaneCount: 3,
    plantMix: [
      { plantType: 'crypt-brown', weight: 0.74 },
      { plantType: 'anubias-nana-clump', weight: 0.26 }
    ],
    assetIds: ['plant-amazon-sword', 'plant-willow-moss']
  },
  {
    id: 'right-rear',
    x: 0.28,
    z: -0.18,
    layer: 'background',
    massRole: 'right-rear',
    plantType: 'crypt-brown',
    baseHeight: 6.12,
    spreadX: 0.2,
    spreadZ: 0.16,
    hueBase: 0.065,
    rotationY: 0.24,
    scale: new THREE.Vector3(0.82, 1.28, 0.8),
    heightMin: 4.96,
    heightMax: 6.82,
    coreCount: 1,
    satelliteCount: 1,
    offshootCount: 1,
    coreRadius: [0.03, 0.12],
    satelliteRadius: [0.14, 0.3],
    offshootRadius: [0.28, 0.48],
    minDistance: 0.062,
    depthLaneCount: 3,
    plantMix: [
      { plantType: 'crypt-brown', weight: 0.78 },
      { plantType: 'anubias-nana-clump', weight: 0.22 }
    ],
    assetIds: ['plant-amazon-sword', 'plant-willow-moss']
  }
]

export const NATURE_SHOWCASE_PLANT_CLUSTER_DEFINITIONS: PlantClusterDefinition[] = [
  {
    id: 'left-rear',
    x: -0.356,
    z: -0.24,
    layer: 'background',
    massRole: 'left-rear',
    plantType: 'amazon-sword',
    baseHeight: 6.62,
    spreadX: 0.14,
    spreadZ: 0.14,
    hueBase: 0.264,
    rotationY: -0.36,
    scale: new THREE.Vector3(0.8, 1.24, 0.78),
    heightMin: 5.82,
    heightMax: 7.08,
    coreCount: 1,
    satelliteCount: 2,
    offshootCount: 1,
    coreRadius: [0.03, 0.16],
    satelliteRadius: [0.12, 0.28],
    offshootRadius: [0.24, 0.42],
    minDistance: 0.058,
    depthLaneCount: 4,
    plantMix: [
      { plantType: 'amazon-sword', weight: 0.26 },
      { plantType: 'stem-green-bush', weight: 0.5 },
      { plantType: 'hygrophila-rear', weight: 0.24 },
      { plantType: 'matsumo', weight: 0.12 }
    ],
    assetIds: ['plant-amazon-sword', 'plant-hygrophila-rear', 'plant-hygrophila-rear', 'plant-matsumo', 'plant-willow-moss']
  },
  {
    id: 'left-mid-broadleaf',
    x: -0.26,
    z: 0.02,
    layer: 'midground',
    massRole: 'left-shoulder',
    plantType: 'javafern-large',
    baseHeight: 6.12,
    spreadX: 0.28,
    spreadZ: 0.22,
    hueBase: 0.276,
    rotationY: -0.3,
    scale: new THREE.Vector3(1.02, 1.16, 0.96),
    heightMin: 5.06,
    heightMax: 6.42,
    coreCount: 1,
    satelliteCount: 5,
    offshootCount: 3,
    coreRadius: [0.03, 0.12],
    satelliteRadius: [0.1, 0.26],
    offshootRadius: [0.18, 0.36],
    minDistance: 0.05,
    depthLaneCount: 4,
    plantMix: [
      { plantType: 'javafern-large', weight: 0.32 },
      { plantType: 'javafern-narrow', weight: 0.26 },
      { plantType: 'anubias-petite-clump', weight: 0.18 },
      { plantType: 'anubias-nana-clump', weight: 0.24 }
    ],
    assetIds: ['plant-amazon-sword', 'plant-matsumo', 'plant-willow-moss', 'plant-willow-moss']
  },
  {
    id: 'center-left-fern-mass',
    x: -0.14,
    z: -0.02,
    layer: 'midground',
    massRole: 'driftwood-backfill',
    plantType: 'javafern-large',
    baseHeight: 5.18,
    spreadX: 0.28,
    spreadZ: 0.22,
    hueBase: 0.284,
    rotationY: -0.02,
    scale: new THREE.Vector3(0.94, 1.08, 0.9),
    heightMin: 4.12,
    heightMax: 5.62,
    coreCount: 1,
    satelliteCount: 5,
    offshootCount: 3,
    coreRadius: [0.03, 0.11],
    satelliteRadius: [0.08, 0.24],
    offshootRadius: [0.18, 0.36],
    minDistance: 0.042,
    depthLaneCount: 4,
    plantMix: [
      { plantType: 'javafern-large', weight: 0.32 },
      { plantType: 'javafern-narrow', weight: 0.32 },
      { plantType: 'anubias-nana-clump', weight: 0.22 },
      { plantType: 'anubias-petite-clump', weight: 0.14 }
    ],
    assetIds: ['plant-amazon-sword', 'plant-matsumo', 'plant-willow-moss', 'plant-willow-moss']
  },
  {
    id: 'right-mid-crypt',
    x: 0.08,
    z: -0.02,
    layer: 'midground',
    massRole: 'mid-right-backfill',
    plantType: 'crypt-brown',
    baseHeight: 2.94,
    spreadX: 0.12,
    spreadZ: 0.1,
    hueBase: 0.062,
    rotationY: 0.18,
    scale: new THREE.Vector3(0.58, 0.72, 0.58),
    heightMin: 2.48,
    heightMax: 3.56,
    coreCount: 1,
    satelliteCount: 2,
    offshootCount: 1,
    coreRadius: [0.03, 0.12],
    satelliteRadius: [0.1, 0.22],
    offshootRadius: [0.2, 0.32],
    minDistance: 0.054,
    depthLaneCount: 3,
    plantMix: [
      { plantType: 'crypt-brown', weight: 1 }
    ],
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'right-rear',
    x: 0.12,
    z: -0.18,
    layer: 'background',
    massRole: 'right-rear',
    plantType: 'crypt-brown',
    baseHeight: 3.92,
    spreadX: 0.1,
    spreadZ: 0.12,
    hueBase: 0.058,
    rotationY: 0.22,
    scale: new THREE.Vector3(0.6, 0.82, 0.6),
    heightMin: 3.24,
    heightMax: 4.44,
    coreCount: 1,
    satelliteCount: 2,
    offshootCount: 1,
    coreRadius: [0.03, 0.12],
    satelliteRadius: [0.12, 0.24],
    offshootRadius: [0.2, 0.34],
    minDistance: 0.056,
    depthLaneCount: 3,
    plantMix: [
      { plantType: 'crypt-brown', weight: 1 }
    ],
    assetIds: ['plant-amazon-sword']
  },
  {
    id: 'left-foot',
    x: -0.22,
    z: 0.14,
    layer: 'foreground',
    massRole: 'left-foot',
    plantType: 'anubias-petite-clump',
    baseHeight: 1.28,
    spreadX: 0.08,
    spreadZ: 0.08,
    hueBase: 0.252,
    rotationY: -0.1,
    scale: new THREE.Vector3(0.54, 0.5, 0.52),
    heightMin: 0.9,
    heightMax: 1.36,
    coreCount: 1,
    satelliteCount: 1,
    offshootCount: 0,
    coreRadius: [0.02, 0.07],
    satelliteRadius: [0.08, 0.16],
    offshootRadius: [0.18, 0.28],
    minDistance: 0.048,
    depthLaneCount: 2,
    plantMix: [
      { plantType: 'anubias-petite-clump', weight: 1 }
    ],
    assetIds: ['plant-willow-moss']
  }
]
